version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - echo Build started on `date`
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet tool update -g Amazon.Lambda.Tools
      - dotnet lambda deploy-serverless --project-location "FarmsToFeedUs.Api" --msbuild-parameters "/p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true --self-contained false"
      - dotnet lambda deploy-serverless --project-location "FarmsToFeedUs.ImportService" --msbuild-parameters "/p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true --self-contained false"