version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - dotnet test
      - dotnet lambda deploy-serverless --project-location "FarmsToFeedUs.Api" --msbuild-parameters "/p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true --self-contained false"
      - dotnet lambda deploy-serverless --project-location "FarmsToFeedUs.ImportService" --msbuild-parameters "/p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true --self-contained false"
      - dotnet publish .\FarmsToFeedUs.Client\

artifacts:
  name: client
  files:
    - 'FarmsToFeedUs.Client/bin/Release/netstandard2.1/publish/**/*'