---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Live
Resources:
  ListApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: FarmsToFeedUs.Api::FarmsToFeedUs.Api.ListFunction::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      Description: List farms api
      MemorySize: 256
      Timeout: 20
      Tracing: Active
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
      - AWSLambdaFullAccess
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /farms
            Method: GET