---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Live
Resources:
  ListApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: FarmsToFeedUs.Api::FarmsToFeedUs.Api.ListFunction::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      Description: List farms api
      MemorySize: 256
      Timeout: 20
      Tracing: Active
      Environment:
        Variables:
          Environment: !Ref Environment
      Policies:
      - AWSLambdaFullAccess
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /farms
            Method: GET
  S3BucketHtml:
    Type: AWS::S3::Bucket
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3BucketHtml
  CloudFrontReadPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketHtml
      PolicyDocument:
        Statement:
        - Action: 's3:GetObject'
          Effect: Allow
          Resource: !Sub 'arn:aws:s3:::${S3BucketHtml}/*'
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        CustomErrorResponses:
        - ErrorCode: 403 # not found
          ResponseCode: 404
          ResponsePagePath: '/error'
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt 'S3BucketHtml.DomainName'
          Id: s3
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: s3
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https